### ISSUE TITLE
This repository is over its data quota (Git LFS)

### ISSUE THREAD

**Issue by dakota-palmer** [ilo21/fpExplorer#1]
Hi, I can download the repository fine as a .zip but if I try to clone it to GitHub Desktop I'm getting an error related to Git's Large File Storage (LFS). I think you may need to increase the LFS limit if feasible or maybe find another way to share example data? The error follows:

Downloading ExampleData/SubjectExperiment/Event based GCaMP6f (+artifact)/Fear test/Fear_test-191219_40-191219-103822.Tbk (292 KB)
Error downloading object: ExampleData/SubjectExperiment/Event based GCaMP6f (+artifact)/Fear test/Fear_test-191219_40-191219-103822.Tbk (4a5af76): Smudge error: Error downloading ExampleData/SubjectExperiment/Event based GCaMP6f (+artifact)/Fear test/Fear_test-191219_40-191219-103822.Tbk (4a5af76810603f06be1a4cb20d4dde9354b0ac81e370f0e637fcffbc5b73a8fd): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by ilo21** [comment]
Thank you for trying our app. This error indeed appeared also to me this month. We are currently discussing alternative ways to share the example data. Unfortunately, if you downloaded zip file you will not get any example TDT data. I have removed the folder with example data from this github repository for now. And you should be able to clone it without any issues, while we are figuring out how to share large files better. 
Thank you in advance for your patience
